Preliminary circleci configuration.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,7 +2,7 @@ defaults: &defaults
   environment:
     GOOGLE_PROJECT_ID: planet-4-151612
   docker:
-    - image: gcr.io/planet-4-151612/circleci-base:latest
+    - image: gcr.io/planet-4-151612/circleci-base:0.3.0
   working_directory:  /home/circleci/app
 
 version: 2
@@ -16,35 +16,42 @@ jobs:
       - setup_remote_docker
 
       - run:
+          name: Determine branch
+          command: |
+            if [[ -z "${CIRCLE_BRANCH}" ]] && [[ "${CIRCLE_TAG}" ]]
+            then
+              # Find which remote branch contains the current commit
+              git remote update
+              CIRCLE_BRANCH=$(git branch -r --contains ${CIRCLE_SHA1} | grep -v 'HEAD' | awk '{split($1,a,"/"); print a[2]}')
+              # Checkout that branch / tag
+              git checkout ${CIRCLE_BRANCH}
+              if [[ "$(git rev-parse HEAD)" = "${CIRCLE_SHA1}" ]]
+              then
+                echo "${CIRCLE_BRANCH}" > /tmp/workspace/var/circle-branch-name
+                export CIRCLE_BRANCH
+              else
+                >&2 echo "Found the wrong commit!"
+                >&2 echo "Wanted: ${CIRCLE_SHA1}"
+                >&2 echo "Found:  $(git rev-parse HEAD)"
+                >&2 echo "Could not reliably determine branch for tag ${CIRCLE_TAG}, attempting to continue ..."
+                exit 0
+              fi
+            fi
+
+      - run:
           name: Configure gcloud
           command: |
             ${HOME}/scripts/activate-gcloud-account.sh
-      - run:
-          name: Configure cloudbuild substitutions
-          command: |
-            # Rewrite cloudbuild variables
-            SUBSTITUTIONS=(
-              "_BUILD_NUM=${CIRCLE_BUILD_NUM}"
-              "_BUILD_NAMESPACE=${BUILD_NAMESPACE:-'gcr.io'}" \
-              "_BUILD_TAG=${BUILD_TAG:-${CIRCLE_TAG:-${CIRCLE_BRANCH}}}" \
-              "_GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}" \
-              "_SHORT_SHA=$(git rev-parse --short HEAD)" \
-            )
-
-            SUBSTITUTIONS_PROCESSOR="$(printf "%s," "${SUBSTITUTIONS[@]}")"
-            SUBSTITUTIONS_STRING="${SUBSTITUTIONS_PROCESSOR%,}"
-            export SUBSTITUTIONS_STRING
 
       - run:
-          name: Building platform containers on gcr.io
+          name: Build application
           command: |
-            # Submit dev build
-            time ${HOME}/google-cloud-sdk/bin/gcloud container builds submit \
-              cloudbuild-dev.yaml \
-              --verbosity=${VERBOSITY:-'warning'} \
-              --timeout=${BUILD_TIMEOUT:-'10m'} \
-              --config cloudbuild-${BUILD_ENVIRONMENT:-'dev'}.yaml \
-              --substitutions ${SUBSTITUTIONS_STRING}
+            ./build.sh -r
+
+      - persist_to_workspace:
+          root: /tmp/workspace
+          paths:
+            - var
 
   test:
     <<: *defaults
